[theme]
base = "light"
# Primary color for buttons, highlights, and active elements
primaryColor = "#338AFF"              # Blue buttons and accents
# Backgrounds
backgroundColor = "#FDFBF7"           # Main background (cream)
secondaryBackgroundColor = "#a9c5eb"  # Sidebar / navigation (blue)
# Text color (auto-applies where background is light)
textColor = "#364153"                 # Text for cream backgrounds
# Font
font = "Inter"
